### ISSUE TITLE
migrate to new git structure and release package(s)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/v4r#15]

**Comment by marc-hanheide** [comment]
OK, from now on jenkins performs automated builds for all pull requests and commits to the "master" branch. You should get emails about the progress so you can use this to fix any outstanding issues and it will make sure that your code compiles properly on a "fresh" Ubuntu 14.04 64bit.

**Comment by ToMadoRe** [comment]
okay, so as far as I understand, jenkins complains about missing ceres and glew. How can I trigger a new build process on jenkins after changing code in V4R?

**Comment by hawesie** [comment]
:+1:
