### ISSUE TITLE
V4R needs opencv_nonfree

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/v4r#17]
Since we are using SIFT for all kind of stuff, we need the non_free module of OpenCV, which does not come by just installing opencv with apt-get install libopencv-dev
We either have to install it from source and enable the non-free module or by adding another ppa as described in 
http://stackoverflow.com/questions/27481849/include-nonfree-opencv-2-4-10-on-ubuntu (haven't tried this solution yet)
otherwise I get the following linker error: 
```
..../lib/libv4r_object_modelling.so: undefined reference to `cv::SIFT::SIFT(int, int, double, double, double)'
collect2: error: ld returned 1 exit status
```

**Comment by OMARI1988** [comment]
I have installed it from source before and it works nicely, just follow the
following:

- mkdir ~/opencv

- cd ~/opencv

- git clone https://github.com/Itseez/opencv.git

- git clone https://github.com/Itseez/opencv_contrib.git

- cd opencv-3.0.0

- mkdir build

- cd build

-- (make sure to change the directory to opencv_contrib in your pc in the
next step)
- cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D
WITH_CUBLAS=ON -D WITH_CUFFT=ON -D WITH_EIGEN=OFF -D WITH_OPENGL=ON -D
WITH_QT=ON -D WITH_TBB=ON -D BUILD_DOCS=ON -D BUILD_EXAMPLES=ON -D
BUILD_TESTS=ON -D CUDA_ARCH_BIN="3.0" -D
OPENCV_EXTRA_MODULES_PATH=/home/omari/opencv/opencv_contrib/modules ..
-DBUILD_opencv_cvv=OFF

- make -j7

- sudo make install

- sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

- sudo ldconfig

and that's it, hope this helps :)

Muhannad

On Tue, Jul 28, 2015 at 4:01 PM, Thomas Fäulhammer <notifications@github.com

**Comment by cdondrup** [comment]
Now I wish I would have written the guide on how to use fpm to create debian packages from source code when @marc-hanheide told me. I'll do that now, just give me a few minutes. That might actually help.

**Comment by cdondrup** [comment]
This might help: https://github.com/strands-project/strands_management/wiki/Creating-debian-packages-from-source-using-fpm

**Comment by marc-hanheide** [comment]
Just to add my two cents: ppa is not a good option, neither is compiling from source, as both require manual steps. Creating a package using fpm is better, but in fact opencv provides its one way to simply build Debian packages using `cpack`, IIRC. So, it should be easy to create your own opencv Debian package, send it to me, and I'll host it. Just make sure the package is names slightly differently (e.g. `_strands` suffix). Still, not ideal... Can the "SIFT" stuff be packages separately?

**Comment by mzillich** [comment]
We also thought about packaging SIFT separately. We are still looking into this. This would be the cleanest option.

**Comment by marc-hanheide** [comment]
I would strongly prefer that, even, maybe as part of V4R...

**Comment by ToMadoRe** [comment]
the other option would be to use the SiftGPU module as default, which is already included in V4R as 3rdparty package (you can basically choose between SiftGPU and OpenCV's non-free Sift). But therefore we would need a system with GPU. How would Jenkins manage this? SiftGPU is the preferred option anyway.

**Comment by marc-hanheide** [comment]
Does one need a GPU to *compile* it? I suppose not. So then it shouldn't make a difference up to the point that it cannot run any tests then.

**Comment by marc-hanheide** [comment]
@ToMadoRe can you comment on my question? Would be important to know.

**Comment by ToMadoRe** [comment]
no, it does not need a GPU to compile... SIFTgpu will however throw a runtime error when it tries to open a OpenGL context

**Comment by marc-hanheide** [comment]
OK, in general, I think it would be best if GPU is optional, if you accommodate that. But from jenkins PoV it's not a problem as long as you don't define any unit test that need SiftGPU (as currently it doesn't have any GPU).

**Comment by marc-hanheide** [comment]
We solved this, didn't we?

**Comment by ToMadoRe** [comment]
well, still the same situation. It compiles fine but will throw a runtime error on machines without OpenGL support (i.e. without GPUs).
For these setups, one would need to compile from source and link to the appropriate OpenCV version (with non-free modules).

**Comment by marc-hanheide** [comment]
OK, but then this isn't really an issue anymore, right?

**Comment by ToMadoRe** [comment]
okay, maybe we can close the issue for now
