### ISSUE TITLE
v4r needs newer PCL

### ISSUE THREAD

**Issue by cburbridge** [strands-project/v4r#18]
During the review we introduced the need for a newer version of PCL than available through the repositories and had to install from source. It was a bit messy, having to be careful not to mix the version of PCL between side-pcs and main pc destined packages.

Is there a better solution? How can we release this if we don't also switch to the newer PCL project wide?

**Comment by mzillich** [comment]
@ToMadoRe We no longer depend on a specific PCL version, right? The normal version that comes as a dependency of indigo should be ok.

**Comment by cburbridge** [comment]
It used to depend on a newer version when we used Hydro/12.04 and then it was fantastic when we moved to Indigo/14.04 because that painful dependency vanished. But then, at the review, we had to again get a (even) newer version of PCL...

**Comment by ToMadoRe** [comment]
Actually, we never tried to compile our new v4r version with a PCL version other than 1.7.2 or 1.8. As far as I can remember,  there was an issue with PCL octree that was solved in 1.7.2. So we probably run into this bug again at some point and it makes sense to upgrade PCL. @taketwo should know the details though.

**Comment by taketwo** [comment]
When we released 1.7.2 I spent two evenings putting together the [list of changes](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.7.2). As you can see, it's quite vast. I don't know into which of the fixed bugs you (we) already ran into, but chances are that sooner or later we meet with some of them anyway.

Given that 1.7.2 is available in a PPA, what would it take for us to switch to it? If the effort is relatively small, I'd go for it.

**Comment by ToMadoRe** [comment]
Maybe we should add @marc-hanheide to this conversation

**Comment by cburbridge** [comment]
But if we use the PPA version, then the ROS packages that are linked against the non-PPA older version could be a problem??? Would it mean we have to compile any of the standard ROS packages that use PCL against the version we use?

**Comment by taketwo** [comment]
I remember making ABI compatibility checks before the release; they indicated that the everything is fine...

**Comment by marc-hanheide** [comment]
The only problem with PPAs is that require another step for people to use our software, and we cannot say that we base our software on Ubuntu 14.04LTS. Fine for most developers, a burden for others, and another problem to have our software released to ROS, as obviously, there needs to be a standard basis for software releases. So, it would certainly be better, if we could use the deployed version. If we really need the newer one, then we'd have to find a way around it. PPA is one, releasing our own "suffixed" PCL is probably better, not to conflict with installed PCLs.

**Comment by taketwo** [comment]
Releasing our own PCL sounds interesting, we can even take the master branch with all bug fixes accumulated since 1.7.2. Are there any serious deficits for this solution?

**Comment by marc-hanheide** [comment]
Nothing I can think of. As long as it's ABI compatible it should be absolutely fine.

**Comment by marc-hanheide** [comment]
Is this still an issue?

**Comment by ToMadoRe** [comment]
Yes, I think we should use the new PCL version 1.8 as many bugs have been fixed (https://github.com/PointCloudLibrary/pcl/blob/master/CHANGES.md)
@taketwo wanted to release it soon, right?

**Comment by taketwo** [comment]
Yes, it should be released soon.
Note, however, that this will require some work on V4R side. Our library does not compile together with 1.8 at the moment because of some breaking changes.
