### ISSUE TITLE
CMake Error: Unable to find SuitSparse

### ISSUE THREAD

**Issue by kunzel** [strands-project/v4r#3]
Hi,

I've tried to compile v4r, but I was getting an error (see below). 

I have a compiled a version of PCL in ~/v4r_pcl as it is described in the Readme file  and I 've created a separate catkin workspace for v4r in ~/v4r_catkin_ws. Is there anything else to configure? 

Any idea what the problem might be? The path on the second line below looks strange. 

thanks!

[..]
-- ~/v4r_pcl/build
-- ~/v4r_pcl/build/home/lars/v4r_catkin_ws/src/v4r/faat_framework/cmake
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_2D
-- looking for PCL_FEATURES
-- looking for PCL_ML
-- looking for PCL_SEGMENTATION
-- looking for PCL_GEOMETRY
-- looking for PCL_VISUALIZATION
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_KEYPOINTS
-- looking for PCL_SURFACE
-- looking for PCL_TRACKING
-- looking for PCL_STEREO
-- looking for PCL_APPS
-- Found PCL: /usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_mpi-mt.so;/usr/lib/libboost_serialization-mt.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_common.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_common.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_octree.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_octree.so;/usr/lib/libOpenNI.so;vtkCommon;vtkRendering;vtkHybrid;vtkCharts;optimized;/home/lars/v4r_pcl/build/lib/libpcl_io.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_io.so;optimized;/usr/lib/libflann_cpp_s.a;debug;/usr/lib/libflann_cpp_s.a;optimized;/home/lars/v4r_pcl/build/lib/libpcl_kdtree.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_kdtree.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_search.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_search.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_sample_consensus.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_sample_consensus.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_filters.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_filters.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_features.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_features.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_ml.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_ml.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_segmentation.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_segmentation.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_visualization.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_visualization.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_registration.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_registration.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_recognition.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_recognition.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_keypoints.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_keypoints.so;optimized;/usr/lib/libqhull.so;debug;/usr/lib/libqhull.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_surface.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_surface.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_tracking.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_tracking.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_stereo.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_stereo.so;optimized;/home/lars/v4r_pcl/build/lib/libpcl_apps.so;debug;/home/lars/v4r_pcl/build/lib/libpcl_apps.so;/usr/lib/libboost_system-mt.so;/usr/lib/libboost_filesystem-mt.so;/usr/lib/libboost_thread-mt.so;/usr/lib/libboost_date_time-mt.so;/usr/lib/libboost_iostreams-mt.so;/usr/lib/libboost_mpi-mt.so;/usr/lib/libboost_serialization-mt.so;optimized;/usr/lib/libqhull.so;debug;/usr/lib/libqhull.so;/usr/lib/libOpenNI.so;optimized;/usr/lib/libflann_cpp_s.a;debug;/usr/lib/libflann_cpp_s.a;vtkCommon;vtkRendering;vtkHybrid;vtkCharts (Required is at least version "1.7")
-- CUDA WAS NOT FOUND!!
CMake Error at v4r/faat_framework/cmake/find_suitesparse.cmake:125 (MESSAGE):
  Unable to find SuiteSparse
Call Stack (most recent call first):
  v4r/faat_framework/utils/sparselm-1.3/CMakeLists.txt:43 (include)

-- Configuring incomplete, errors occurred!
Invoking "cmake" failed

**Comment by marc-hanheide** [comment]
again, this should be fixed in #16 in the future.
