### ISSUE TITLE
libsvm missing in binary build

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/v4r#30]
the build of Debian packages failed (see https://lcas.lincoln.ac.uk/jenkins/job/ros-indigo-v4r_binarydeb_trusty_amd64/11/console):

```
dpkg-shlibdeps: error: couldn't find library libsvm.so.2 needed by debian/ros-indigo-v4r/opt/ros/indigo/lib/libv4r_ml.so.1.0.0
```

Seems `libsvm.so` is not declared as a dependency...

**Comment by marc-hanheide** [comment]
Right... I just noticed you build it from source... Is that even needed, @taketwo? And then the problem appears to be that you don't install the library?

**Comment by ToMadoRe** [comment]
@marc-hanheide: Could you add libsvm-dev to https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/base.yaml?
I think this would solve our problems.

**Comment by taketwo** [comment]
Yeah, we build it from source. And we are not sure why, actually. The should be no reason why the default Ubuntu package won't work. I'll try it now and update _CMake_ scripts as needed.

**Comment by marc-hanheide** [comment]
ok. if there's no need to build it then let's user the packages. I'll add it to rosdep as `libsvm`, so you should add that the `package.xml`
