### ISSUE TITLE
cannot build examples

### ISSUE THREAD

**Issue by jontromanab** [strands-project/v4r#33]
While I was trying to build v4r, the build process stopped showing this message. I could not figure out the issue with libv4r_tomgine.so.1.0.0
here is the error message:
Linking CXX executable ../../bin/example-classifyPCD_by_ESF
../../lib/libv4r_tomgine.so.1.0.0: undefined reference to `aiScene::aiScene()'
../../lib/libv4r_tomgine.so.1.0.0: undefined reference to `aiScene::~aiScene()'
../../lib/libv4r_tomgine.so.1.0.0: undefined reference to `aiMaterial::aiMaterial()'
../../lib/libv4r_tomgine.so.1.0.0: undefined reference to `aiMaterial::AddProperty(aiString const*, char const*, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/example-classifyPCD_by_ESF] Error 1
make[1]: *** [samples/examples/CMakeFiles/example_classifyPCD_by_ESF.dir/all] Error 2
make: *** [all] Error 2

**Comment by ToMadoRe** [comment]
Yes, we realized that issue when using the Debian Assimp version. It should work when installing Assimp from Source. We are working on a new version of TomGine but this will take two more weeks probably. In the meantime, you can either try to install assimp from source or just delete ``` classifyPCD_by_ESF.cpp``` in the samples folder.

**Comment by jontromanab** [comment]
I have built the package without the classifyPCD_by_ESF.cpp file. But now when I am building the building v4r_ros_wrapper package it is showing the problem with tomgine. Please let me know when you have come up with a new tomgine package.

Here is the error message with the v4r_ros_wrapper package:
Linking CXX executable /root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service
CMakeFiles/recognition_service.dir/src/recognizer_ros.cpp.o: In function v4r::SingleViewRecognizer::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> const>)': /opt/ros/indigo/include/v4r/recognition/singleview_object_recognizer.h:328: undefined reference tov4r::common::computeNormals(boost::shared_ptrpcl::PointCloud<pcl::PointXYZRGB const> const&, boost::shared_ptrpcl::PointCloud<pcl::Normal >&, int)'
/opt/ros/indigo/lib/libv4r_tomgine.so.1.0: undefined reference to `XGetXCBConnection'
collect2: error: ld returned 1 exit status
make[2]: *** [/root/catkin_ws/devel/lib/singleview_object_recognizer/recognition_service] Error 1
make[1]: *** [v4r_ros_wrappers/singleview_object_recognizer/CMakeFiles/recognition_service.dir/all] Error 2
make: *** [all] Error 2


Thank you for replying.

**Comment by marc-hanheide** [comment]
should also be fixed now, right? Re-open if still an issue now after V4R 1.0.11 is released.
