### ISSUE TITLE
Add a CITATION file to the repo

### ISSUE THREAD

**Issue by severin-lemaignan** [strands-project/v4r#47]
It would be very convenient to have a CITATION file at the root of the repo with the references to the academic publications corresponding to the various bits of V4R.

One example of such a file:
https://github.com/severin-lemaignan/dialogs/blob/master/CITATION

**Comment by ToMadoRe** [comment]
Sure, I have created such file now. To be extended...
https://github.com/strands-project/v4r/commit/372f7ebfe5a5906e79d8fb828b14e2aadf8aa6ac
