### ISSUE TITLE
Compiler error on Debian testing/gcc 6.3

### ISSUE THREAD

**Issue by nxdefiant** [strands-project/v4r#74]
1. 
> MvLMIcp.cpp:166:40: error: no matching function for call to 'min(float, double&)'

Seems like sqrt() is returning a float that needs to be converted in double. This problem occurs multiple time in this file.

2.
> compute_recognition_rate.cpp:153:5: error: 'iota' is not a member of 'std'

Needs
`#include <numeric>`

**Comment by ToMadoRe** [comment]
sorry for the super late reply but this should be fixed in the new V4R version (https://rgit.acin.tuwien.ac.at/v4r/v4r/)
